version: '3'

services:
  fe_build:
    image: 'node:18.20-slim'
    restart: always
    working_dir: ${REACT_BUILD_WORK_DIR}
    container_name: ${REACT_BUILD_CONTAINER_NAME}
    volumes:
      - .:${REACT_BUILD_WORK_DIR}
    entrypoint: ['sh', './scripts/develop/build.sh']

  fe_develop:
    image: 'bitnami/nginx:1.25.4'
    container_name: ${REACT_CONTAINER_NAME}
    ports:
      - ${REACT_PORT}:80
    restart: always
    volumes:
      - ${REACT_APPLICATION}:/app
      - ${REACT_NGINX_CONF}:/opt/bitnami/nginx/conf/nginx.conf:ro
      - /etc/localtime:/etc/localtime:ro
