export { default as ApartmentPage } from './apartment';
export { default as LoginPage } from './auth/sign-in';
export { default as RegisterPage } from './auth/sign-up';
export { default as BillPage } from './bill';
export { default as MessagePage } from './message';
export { default as Notification } from './notification';
export { default as SettingPage } from './setting';
export { default as WaterMeter } from './water-meter';
export { default as WelcomePage } from './welcome';
